name: build

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Run CI
        run: |
          npm install
          npm run ci

      - name: Upload Snapshot
        if: ${{ failure() }}
        run: |
          npm run upload ${{ github.workspace }} ${{ secrets.OSS_REGION }} ${{ secrets.OSS_ACCESS_KEY_ID }} ${{ secrets.OSS_ACCESS_KEY_SECRET }} ${{ secrets.OSS_BUCKET }}

      - name: Update coverall
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
